name: Analyze Instagram Profile

on:
  workflow_dispatch:
    inputs:
      profile_url:
        description: 'Public Instagram profile URL'
        required: true
        default: 'https://www.instagram.com/bwhockey18/'
      limit_posts:
        description: 'How many recent posts to sample'
        required: false
        default: '12'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ca-certificates fonts-liberation libnss3 libatk-bridge2.0-0 libdrm2 \
            libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libgbm1 libpango-1.0-0 \
            libasound2 libxrandr2 libatk1.0-0 libgtk-3-0 libxshmfence1

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright pandas numpy beautifulsoup4 lxml

      - name: Install Playwright browser
        run: python -m playwright install --with-deps chromium

      - name: Run analysis
        env:
          PROFILE_URL: ${{ github.event.inputs.profile_url }}
          LIMIT_POSTS: ${{ github.event.inputs.limit_posts }}
        run: |
          mkdir -p reports scripts
          python scripts/ig_analyze.py "${PROFILE_URL}" "${LIMIT_POSTS}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: instagram-report
          path: |
            reports/summary.json
            reports/summary.csv
            reports/posts.csv
